#!/usr/bin/env python3
from pathlib import Path
import re, sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")

css = '\n  /* REVIEWED LAYOUT OVERRIDES — deployed from the approved HTML */\n  .color-dot-row{\n    display:flex; gap:clamp(8px,3vw,72px); flex-wrap:nowrap; flex-shrink:0;\n    justify-content:flex-start; padding-right:clamp(0px,2.5vw,40px); width:100%; min-width:0;\n  }\n  .color-dot-row .color-dot{ flex:1 1 0; width:auto; min-width:0; max-width:52px; }\n\n  .settings-row{ display:flex; align-items:stretch; gap:20px; flex-wrap:wrap; padding-right:56px; }\n  .settings-sliders{ display:flex; flex-direction:column; gap:38px; flex:1 1 620px; width:100%; max-width:720px; min-width:0; }\n  .settings-sliders .slider-row{\n    display:grid; grid-template-columns:minmax(280px,1fr) 148px; align-items:center;\n    gap:18px; width:100%;\n  }\n  .settings-sliders .slider-row label,\n  .settings-sliders .intensity-row label{\n    grid-column:2; grid-row:1; min-width:0; white-space:nowrap;\n  }\n  .settings-sliders .slider-row input[type=range]{\n    grid-column:1; grid-row:1; width:100%; max-width:none; min-width:0;\n  }\n  .anim-sq svg, .center-img-btn svg{\n    width:28px; height:28px; stroke:currentColor; stroke-width:2; fill:none;\n    stroke-linecap:round; stroke-linejoin:round;\n  }\n\n  @media (max-width:700px){\n    .image-columns{ align-items:stretch; width:100%; }\n    .image-col-main, .image-col-anim{ width:100%; max-width:100%; }\n    .color-dot-row{\n      justify-content:center; gap:clamp(5px,2vw,12px); width:100%; max-width:360px;\n      padding-inline:0; margin-inline:auto; align-self:center;\n    }\n    .color-dot-row .color-dot{\n      flex:0 1 52px; width:clamp(42px,12vw,52px); max-width:52px;\n    }\n    .anim-grid-sq{\n      display:grid; grid-template-columns:repeat(7,minmax(0,1fr)); grid-template-rows:1fr;\n      gap:6px; width:min(100%,380px); max-width:380px; margin-inline:auto; align-self:center;\n    }\n    .anim-grid-sq > .center-img-btn{\n      grid-column:auto; grid-row:auto; width:100%; height:auto; aspect-ratio:1;\n    }\n    .anim-sq{ width:100%; max-width:none; aspect-ratio:1; border-radius:10px; font-size:0; }\n    .settings-row{ padding-right:0; width:100%; max-width:100%; overflow:visible; }\n    .settings-sliders{ flex:1 1 auto; width:100%; max-width:100%; min-width:0; }\n    .settings-sliders .slider-row{\n      display:grid; grid-template-columns:minmax(0,1fr) minmax(118px,auto);\n      align-items:center; gap:12px; width:100%; min-width:0;\n    }\n    .settings-sliders .slider-row label,\n    .settings-sliders .intensity-row label{\n      grid-column:2; grid-row:1; flex:none; width:auto; min-width:0; white-space:nowrap;\n    }\n    .settings-sliders .slider-row input[type=range]{\n      grid-column:1; grid-row:1; width:100%; max-width:none; min-width:0;\n      box-sizing:border-box; margin-inline:6px;\n    }\n  }\n'
if "REVIEWED LAYOUT OVERRIDES" not in text:
    idx = text.find("</style>")
    if idx < 0:
        raise SystemExit("style closing tag not found")
    text = text[:idx] + css + "\n" + text[idx:]

anim = '              <div class="anim-grid-sq" id="animGrid" style="margin-top:0;">\n                <button class="anim-sq active" data-v="zoomIn" title="تكبير تدريجي" aria-label="تكبير تدريجي"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="M20 20l-4.2-4.2M8.5 11h5M11 8.5v5"/></svg></button>\n                <button class="anim-sq" data-v="zoomOut" title="تصغير تدريجي" aria-label="تصغير تدريجي"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="M20 20l-4.2-4.2M8.5 11h5"/></svg></button>\n                <button class="anim-sq" data-v="slideRight" title="انزلاق لليمين" aria-label="انزلاق لليمين"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M14 7l5 5-5 5"/></svg></button>\n                <button class="anim-sq" data-v="slideLeft" title="انزلاق لليسار" aria-label="انزلاق لليسار"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19 12H5M10 7l-5 5 5 5"/></svg></button>\n                <button class="anim-sq" data-v="slideUp" title="انزلاق لأعلى" aria-label="انزلاق لأعلى"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 19V5M7 10l5-5 5 5"/></svg></button>\n                <button class="anim-sq" data-v="slideDown" title="انزلاق لأسفل" aria-label="انزلاق لأسفل"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M7 14l5 5 5-5"/></svg></button>\n                <button type="button" class="anim-sq center-img-btn" id="centerImgBtn" title="توسيط الصورة" aria-label="توسيط الصورة"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3H3v5M16 3h5v5M8 21H3v-5M16 21h5v-5"/><path d="M9 9h6v6H9z"/></svg></button>\n              </div>\n'
text, n = re.subn(r'(?s)              <div class="anim-grid-sq" id="animGrid" style="margin-top:0;">.*?              </div>\n', lambda m: anim, text, count=1)
if n != 1:
    raise SystemExit(f"anim grid replacement count={n}")

draw_image = '  function drawImageLayer(t){\n    tctx.clearRect(0,0,W,H);\n    const im = state.image;\n    if(im.el){\n      const anim = getAnimTransform(t);\n      const introScale = getIntroScale(t);\n      const baseScale = Math.max(FRAME.w/im.naturalW, FRAME.h/im.naturalH);\n      // The manual "التكبير" scale is anchored at 50% X / 25% Y of the\n      // original cover-fitted image, so increasing the slider preserves the\n      // upper part of the photo instead of zooming toward the dead center.\n      const anchorFx = 0.5, anchorFy = 0.25;\n      const coverW = im.naturalW * baseScale;\n      const coverH = im.naturalH * baseScale;\n      const coverCx = FRAME.x + FRAME.w/2 + im.offsetX;\n      const coverCy = FRAME.y + FRAME.h/2 + im.offsetY;\n      const coverDrawX = coverCx - coverW/2;\n      const coverDrawY = coverCy - coverH/2;\n      const manualAnchorX = coverDrawX + anchorFx*coverW;\n      const manualAnchorY = coverDrawY + anchorFy*coverH;\n\n      const manualW = coverW * im.scale;\n      const manualH = coverH * im.scale;\n      const manualDrawX = manualAnchorX - anchorFx*manualW;\n      const manualDrawY = manualAnchorY - anchorFy*manualH;\n\n      const totalExtraScale = anim.scaleFactor * introScale;\n      const dw = manualW * totalExtraScale;\n      const dh = manualH * totalExtraScale;\n\n      const isZoom = (im.anim === "zoomIn" || im.anim === "zoomOut");\n      let drawX, drawY;\n      if(isZoom){\n        // Animation zoom uses the same upper-half anchor as the manual slider.\n        const animAnchorX = manualDrawX + anchorFx*manualW;\n        const animAnchorY = manualDrawY + anchorFy*manualH;\n        drawX = animAnchorX - anchorFx*dw;\n        drawY = animAnchorY - anchorFy*dh;\n      } else {\n        // Keep slide motion intact while preserving the manual upper-half zoom anchor.\n        drawX = manualDrawX - (dw-manualW)/2 + anim.offX;\n        drawY = manualDrawY - (dh-manualH)/2 + anim.offY;\n      }\n      tctx.drawImage(im.el, drawX, drawY, dw, dh);\n    } else {\n      tctx.fillStyle = "#20222f";\n      tctx.fillRect(FRAME.x, FRAME.y, FRAME.w, FRAME.h);\n      tctx.fillStyle = "#6a6d85";\n      tctx.font = "600 32px sans-serif";\n      tctx.textAlign = "center";\n      tctx.fillText("ارفع صورة من تبويب «الصورة»", FRAME.x+FRAME.w/2, FRAME.y+FRAME.h/2);\n    }\n    if(maskImg.complete && maskImg.naturalWidth){\n      tctx.globalCompositeOperation = "destination-in";\n      tctx.drawImage(maskImg, 0, 0, W, H);\n      tctx.globalCompositeOperation = "source-over";\n    }\n    ctx.drawImage(tempCanvas, 0, 0);\n  }\n\n'
text, n = re.subn(r'(?s)  function drawImageLayer\(t\)\{.*?(?=  function wrapLines\(text, font, maxWidth\)\{)', lambda m: draw_image, text, count=1)
if n != 1:
    raise SystemExit(f"drawImageLayer replacement count={n}")

draw_text = '  function drawTextLayers(t){\n    const maxWidth = TEXT_BOX.w;\n    const centerX = TEXT_BOX.x + TEXT_BOX.w/2;\n\n    // If the subline occupies exactly one rendered line, move the complete\n    // headline + subline block 20px lower. Use the full subline text (rather\n    // than the current typewriter reveal) so the block does not jump while\n    // the text is animating in.\n    const sublineLayer = state.texts.find(layer => layer.kind === "subline") || state.texts[1];\n    let singleLineSublineOffset = 0;\n    if(sublineLayer && sublineLayer.text && sublineLayer.text.trim()){\n      const sublineFont = `${sublineLayer.size}px \'PFDinMedium\'`;\n      const fullSublineLines = wrapLines(sublineLayer.text, sublineFont, maxWidth);\n      if(fullSublineLines.length === 1) singleLineSublineOffset = 20;\n    }\n\n    let y = TEXT_BOX.y + singleLineSublineOffset;\n    ctx.direction = "rtl";\n    ctx.textAlign = "center";\n    ctx.textBaseline = "alphabetic";\n\n    const frameNum = t * FPS * DURATION;\n    const revealCounts = computeTypewriterReveal(frameNum);\n\n    state.texts.forEach((layer, idx)=>{\n      const revealed = layer.text.slice(0, revealCounts[idx]);\n      if(!revealed.trim()) return;\n      const family = layer.kind === "headline" ? "\'PFDinXBlack\'" : "\'PFDinMedium\'";\n      const fontStr = `${layer.size}px ${family}`;\n      const lines = wrapLines(revealed, fontStr, maxWidth);\n      const lineHeight = layer.size * 1.28 + (layer.lineSpacing||0);\n\n      ctx.font = fontStr;\n      ctx.fillStyle = layer.color;\n      ctx.shadowColor = "rgba(0,0,0,.45)";\n      ctx.shadowBlur = 14;\n      ctx.shadowOffsetY = 3;\n\n      for(const line of lines){ y += lineHeight; ctx.fillText(line, centerX, y); }\n      y += 1.6;\n    });\n    ctx.shadowBlur = 0; ctx.shadowOffsetY = 0;\n  }\n\n'
text, n = re.subn(r'(?s)  function drawTextLayers\(t\)\{.*?(?=  function drawSwipeIcon\(\)\{)', lambda m: draw_text, text, count=1)
if n != 1:
    raise SystemExit(f"drawTextLayers replacement count={n}")

load_image = '  function loadMainImage(src, filename){\n    const img = new Image();\n    img.onload = ()=>{\n      state.image.el = img;\n      state.image.naturalW = img.naturalWidth;\n      state.image.naturalH = img.naturalHeight;\n      state.image.offsetX = 0;\n      state.image.scale = 1;\n      // Default framing: align the image\'s top edge with the frame top whenever\n      // there is vertical crop room, reducing accidental face cropping on upload.\n      const baseScale = Math.max(FRAME.w/img.naturalWidth, FRAME.h/img.naturalHeight);\n      const fittedH = img.naturalHeight * baseScale;\n      state.image.offsetY = Math.max(0, (fittedH - FRAME.h) / 2);\n      document.getElementById("imgScale").value = 100;\n      document.getElementById("imgScaleVal").textContent = "100%";\n      document.getElementById("mainImageChip").textContent = "✓ "+filename;\n      const thumb = document.getElementById("uploadThumb");\n      thumb.src = src;\n      thumb.style.display = "block";\n      updateOffsetBounds();\n      renderCurrent();\n    };\n    img.src = src;\n  }\n\n'
text, n = re.subn(r'(?s)  function loadMainImage\(src, filename\)\{.*?(?=  document\.getElementById\("mainImageInput"\))', lambda m: load_image, text, count=1)
if n != 1:
    raise SystemExit(f"loadMainImage replacement count={n}")

checks = [
    'grid-template-columns:repeat(7,minmax(0,1fr))',
    'const anchorFx = 0.5, anchorFy = 0.25;',
    'singleLineSublineOffset = 20',
    'y += 1.6;',
    'state.image.offsetY = Math.max(0, (fittedH - FRAME.h) / 2);',
    'aria-label="توسيط الصورة"'
]
missing = [x for x in checks if x not in text]
if missing:
    raise SystemExit("missing approved markers: " + repr(missing))

path.write_text(text, encoding="utf-8")
